WRQ-25865: Updated package dependencies to fix security vulnerabilities
enactjs/eslint-config-enact-proxy pull request #11
Opened 2024-06-26 08:07 UTC by ion-andrusciac-lgp

### Checklist

* [x] I have read and understand the [contribution guide](http://enactjs.com/docs/developer-guide/contributing/)
* [ ] A [CHANGELOG entry](http://enactjs.com/docs/developer-guide/contributing/changelogs/) is included
* [x] I have run automated CLI testing and it is passed
* [ ] This is an API breaking change

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)
Updated dependencies to the latest minor version.

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)
Updated dependencies to the latest minor version.

### Additional Considerations
[//]: # (How should the change be tested?)
[//]: # (Are there any outstanding questions?)
[//]: # (Were any side-effects caused by the change?)

### Links
[//]: # (Related issues, references)
WRQ-25865

### Comments

Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com

2024-06-27 10:45 UTC, stanca-pop-lgp requested changes

2024-06-27 10:45 UTC, stanca-pop-lgp commented on package.json
>  }
```suggestion
}

```

2024-06-27 11:40 UTC, stanca-pop-lgp approved these changes
LGTM

2024-07-02 08:24 UTC, hong6316 approved these changes
👍

2024-07-02 08:24 UTC, merged